# ci only for gitlab to publish docs on gitlab pages

docs:
  stage: deploy
  script:
    - ls -all
    - rm -rf public
    - mkdir public
    - cp -r docs/. public
    - ls -all
  artifacts:
    paths:
      - public
  only:
    - master
