# ci only for gitlab to publish docs on gitlab pages

docs:
  stage: deploy
  script:
    - ls -all
    - mkdir .public
    - cp -r docs/. .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
