language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
#  - TODO: fix code below
#  - npm run test-headless
  - ng build --prod --base-href='https://matsta25.github.io/angular-starter-app/'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-starter-app
  on:
    branch: master
